### PR TITLE
Make it obvious from where given functions come from

### PR DESCRIPTION
**Pull request by kornicameister**

### CODE REVIEW

**Comment by kornicameister** [comment]
Just noticed that's not a typo actually. Wonder if it would make sense to somehow make it obvious that `ok` and `fail` are functions from the same library?

**Comment by stoeffel** [comment]
We could prefix `ok` and `fail` with `Verify` to clarify this. What do you think?

**Comment by michaeljones** [comment]
:+1: I've just been staring at `compose` & `andThen` trying to figure out the difference. Definitely mistook `ok` & `fail` for `Ok` & `Err` initially.

**Comment by kornicameister** [comment]
Yep, sounds like a nice idea :+1:

**Comment by kornicameister** [comment]
Yep, sounds like a nice idea :+1. 
I will try to sit down and maybe check all other examples.

**Comment by kornicameister** [comment]
@stoeffel I actually went a bit further and tried make it explicit in every other corner.

**Pull request merged**
