### PR TITLE
Non empty list for errors

### LINKED ISSUE #21: using a non empty list for errors.
I was wondering if it would be a good idea to ensure that there is always at least one error by using a non-empty list. I like using `(a, List a)` for that to avoid depending on a package. 

```diff
type alias Validator error input verified = 
-    input -> Result (List error) verified
type alias Validator error input verified = 
+    input -> Result (a, List error) verified
```

### PR DESCRIPTION
**Pull request by stoeffel**
fixes #21

### CODE REVIEW

**Comment by stoeffel** [comment]
> Not sure about List.nonEmpty though. In my experiences so far there was no need to to get back the first element

I think it's more about having a guarantee that the list is not empty.

> Also it is unclear if String.notBlank should return similar structure then for consistency.

oh, yes maybe.

> My suggestion would be to not make these 2 changes in the same go.

you are right. I will separate the 2 changes.

**Comment by stoeffel** [comment]
@gyzerok I've separated this into two PRs.

**Comment by gyzerok** [comment]
@stoeffel I came back here for 0.19 update and suddenly realzed this is still open 😅  To be honest I was thinking it was merged already. Should be more careful with GitHub notifications.

**Comment by stoeffel** [comment]
I forgot about it myself :-D

**Comment by stoeffel** [comment]
thanks for publishing

**Pull request merged**
